### ISSUE TITLE
Accessing the creator from outside the class

### ISSUE THREAD

**Issue by ansman** [rharter/auto-value-parcel#101]
I need to access the creator field from an outside class to be able to called `Parcel#createdTypedArrayList(Creator<T> creator)`

My current solution is to add this method:
```java
@NonNull
public static Creator<MyObject> creator() {
    //noinspection unchecked
    return (Creator) AutoValue_MyObject.CREATOR;
}
```

**Comment by rharter** [comment]
While I see the value in this, I don't think I'm on board with building it in because that assumes that **all** instances of the abstract class will be `AutoValue_MyObject`s, but that's not necessarily the case.  Users could implement the abstract class with something else, and then you end up with a `creator()` method that returns something that's unusable for the class.  I think in this specific case requiring this type of method is okay.  I'm open to discussion, though.

**Comment by ansman** [comment]
But you will still have to know the concrete type in order to parcel them so I'm guessing that if you have multiple implementations you'll know which creator method to invoke.

**Comment by rharter** [comment]
As I think about this more, this isn't really something that can be built in, because the user still has to create the public API for it, just like the static factory methods.

**Comment by ansman** [comment]
Yeah, the issue was more that I needed an unchecked cast

**Comment by vanniktech** [comment]
Is it possible to declare an abstract method on your `MyObject`?

```java
@NonNull public abstract Creator<MyObject> creator();
```

Then `auto-value-parcel` will implement it out, since it knows where the creator will be. If you change the implementation of `MyObject`, whatever you're changing to has to override this method and provide a way of returning a Creator.

**Comment by ansman** [comment]
@vanniktech Unfortunately not since you need to access the creator from a static context.

**Comment by rharter** [comment]
The unchecked caste isn't really an `auto-value-parcel` issue, it's that you're trying to convert a `Creator<AutoValue_Foo>` to `Creator<Foo>`.  That's just java.

Unless there's something more to be done here, can we close this issue?

**Comment by ansman** [comment]
Perhaps there isn't anything do be done.
